### ISSUE TITLE
scss

### ISSUE THREAD

**Issue by Huauauaa** [Huauauaa/cheat-sheet#22]

**Comment by Huauauaa** [comment]
## js 中使用 scss
```scss
$text-color: #2c3e50;

:export {
  textColor: $text-color;
}
```

```js
import variables  from './variables.scss';

 console.log(variables);
```

**Comment by Huauauaa** [comment]
## * wildcard
```scss
i[class*='icon-'] {
  font-size: 1rem;
}

i[class^='icon-'] {
  font-size: 1rem;
}
```

**Comment by Huauauaa** [comment]
# 父层级样式

```scss
// @at-root与 & 配合使用
.child {
  @at-root .parent & {
    color: #fff;
  }
}
```
