### ISSUE TITLE
js DOM

### ISSUE THREAD

**Issue by Huauauaa** [Huauauaa/cheat-sheet#31]

**Comment by Huauauaa** [comment]
## 获取样式
- `<el>.style`
- `window.getComputedStyle(<el>, pseudoElt)` , [getComputedStyle](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle)
- `<el>.currentStyle` IE, 返回元素当前应用的最终css属性值
- `<el>.getPropertyValue()

**Comment by Huauauaa** [comment]
# 检测黑暗模式
> prefers-color-scheme
```css
/* light mode */
@media (prefers-color-scheme: light) {
    body {
        background: #f0f0f0;
    }
}

/* dark mode */
@media (prefers-color-scheme: dark) {
    body{
        color: #fff;
        background: #3e3e3e;
    }
}
```
```js
if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
  // dark mode
}
```
