### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Huauauaa** [Huauauaa/cheat-sheet#40]

**Comment by Huauauaa** [comment]
# 省略号
## 一行
```css

overflow:hidden; //超出的文本隐藏
text-overflow:ellipsis; //溢出用省略号显示
white-space:nowrap; //溢出不换行
```

## 两行
```css
overflow: hidden;
text-overflow: ellipsis;
display:-webkit-box; //作为弹性伸缩盒子模型显示。
-webkit-box-orient:vertical; //设置伸缩盒子的子元素排列方式--从上到下垂直排列
-webkit-line-clamp:2; //显示的行
```

**Comment by Huauauaa** [comment]
# avoid autofill
```css
input:-webkit-autofill,
input:-webkit-autofill:focus {
  transition: background-color 600000s 0s, color 600000s 0s;
}
```

**Comment by Huauauaa** [comment]
# hidden scroll
```css
::-webkit-scrollbar {
    display: none;
  }
```

**Comment by Huauauaa** [comment]
# dark vs light
```css
body {
  color: black;
  background: white;
}
@media (prefers-color-scheme: dark) {
  body {
    color: white;
    background: black;
  }
}
```

**Comment by Huauauaa** [comment]
##  通配符 * wildcard
```scss
i[class*='icon-'] {
  font-size: 1rem;
}

i[class^='icon-'] {
  font-size: 1rem;
}
```
